### PR TITLE
Fixed javascript to be compatible with turbolinks

### PR DESCRIPTION
**Pull request by taratip**
Because we installed turbonlinks gem and the original javascript files did not work well with turbolinks. So I made some changes to be compatible with it.

### CODE REVIEW

**Comment by taratip** [comment]
To test this:
When editing a contract, admin will see tab 'Contract' and 'Lawsuit'. When admin clicks on tab 'Lawsuit', admin should be able to see law suit information. When clicking on tab 'Contract', user should see contract information.

**Review by emestabillo — APPROVED** [review]
LGTM 👍 
Thank you for fixing this @taratip ...I think that was me 😄 I kept getting that turbolinks error for upvote.

**Comment by monroemann** [comment]
Not just you @emestabillo .  Chris Van was having the same issue, and couldn't figure it out, so I think that's why turbolinks got disabled.  Anyway, thank you @taratip !!!!

**Review by monroemann — APPROVED** [review]
Works now!

**Pull request merged**
