### PR TITLE
set default user rating calculation

### PR DESCRIPTION
**Pull request by taratip**

### CODE REVIEW

**Comment by monroemann** [comment]
But did you change what I had changed too?   

In the same file, I changed it to this:

  def calculate_historical(val, division)
    if val.nil?
      10
    else
      val/division
    end
  end

Before, you had that 10 as a 0.  Should I put it back to 0?

**Comment by monroemann** [comment]
The reason I changed it: if the contract has no history, then the historical score should be equal to the score of that contract divided by 10, right?  It shouldn't be 0.  In fact, it shouldn't be 10 either.  It should always be the average, right?

**Comment by taratip** [comment]
Yes, please put it back to 0

**Comment by monroemann** [comment]
I just changed it back, and merged it.  Can you please explain to me why it needs to be 0 though?

**Pull request merged**
