### PR TITLE
Merge Latest Changes to Master

### PR DESCRIPTION
**Pull request by monroemann**
Please test and make sure everything still works.  If so, will launch to live heroku site after two reviews.

NOTE: actually test it.  Do not just read the code.  Thanks.

### CODE REVIEW

**Review by chen-robert — DISMISSED** [review]
Looks good to me. Good job team!

**Review by taratip — DISMISSED** [review]
Looks good to me. Upvote button also works great.

**Comment by monroemann** [comment]
I’m confused. Does upvote work now? Was the previous branch merged into development?

**Comment by taratip** [comment]
Yes, it somehow works. User can click upvote button to vote. The upvote branch was also merged into this.

**Comment by monroemann** [comment]
@taratip @emestabillo 

I tried the test app on heroku and:

https://gyazo.com/a8ab4a2af5358421f9d8bcb1a1a08b63

Thoughts?

**Comment by monroemann** [comment]
Not even sure which logs to check.  On heroku?  Do I log into heroku somehow and view logs?

**Comment by taratip** [comment]
You can check log in Heroku. Or you could give me an access and I'll take a look.

**Comment by monroemann** [comment]
@taratip Awesome job creating the database for the test app.  Can you PLEASE post a question on our SO about this that explains how to do it, so that we don't always have to ask you to do it?  Thanks so much!

**Comment by monroemann** [comment]
@chen-robert @taratip @hrbrnd You can approve this.  I just tested the live app, and it seems to work fine.

**Review by taratip — APPROVED** [review]

**Review by chen-robert — APPROVED** [review]

**Comment by chen-robert** [comment]
@monroemann We can merge this now.

**Pull request merged**
