### PR TITLE
Fixed broken volunteer links

### PR DESCRIPTION
**Pull request by chen-robert**
To test, go to `/vounteer` and test the links

### CODE REVIEW

**Review by emestabillo — APPROVED** [review]
LGTM 👍

**Review by monroemann — COMMENTED** [review]
@chen-robert Did you check the link in the nav bar, and anywhere else it may exist too?

**Comment by chen-robert** [comment]
@monroemann Not yet, this is only a quick bugfix for the issues Lija brought up earlier.

**Review by monroemann — APPROVED** [review]
Looks great!  My apologies @chen-robert that it took this long!

**Pull request merged**
