### PR TITLE
Install upvote function

### PR DESCRIPTION
**Pull request by dynnog**

### CODE REVIEW

**Comment by monroemann** [comment]
@taratip @emestabillo Can either of you figure out what the issue is with the upvote?  Emmilie, I know you loooovvvveee debugging!

**Comment by emestabillo** [comment]
@monroemann You didn't specify the error. I made a commit, let me know if that was it. Thanks!

**Comment by monroemann** [comment]
@emestabillo @chen-robert @hrbrnd  I have no idea what the error is either.  This is what it's SUPPOSED to do: 
1. User can click on 'all contracts'
2. Those that are waiting for review have an upvote button next to them that allows a user to upvote them. 
3. Those that have been reviewed cannot be upvoted
4. Those with the highest upvotes will be the ones that we prioritize for reviews

Let's all give it a test and see if it works.  If not, we can search out the bug.

**Comment by emestabillo** [comment]
>1. User can click on 'all contracts'

Is this the same as "All Ratings?" If it is, then yes.

>2. Those that are waiting for review have an upvote button next to them that allows a user to upvote them.
>3. Those that have been reviewed cannot be upvoted

Users can upvote or downvote regardless of status (includes reviewed, waitlisted and update requested) **<--- _BUG_**

>4. Those with the highest upvotes will be the ones that we prioritize for reviews

I suppose this is for admin and not a code related issue?

**Comment by monroemann** [comment]
@emestabillo So that's the issue then: 

1. Users should only be able to upvote, NOT downvote
2. Users should only be able to upvote a contract that has NOT already been reviewed, i.e. only 'waitlisted' or 'update requested'

This is not an admin thing, because users are the ones who will be doing the upvoting.  But admin will also be able to see which contracts people most want reviewed (and users can see this too).

Does that answer your question?  Maybe we can merge this to development and then create a new pull to fix these two issues?

**Comment by hrbrnd** [comment]
> @emestabillo So that's the issue then:
> 
> 1. Users should only be able to upvote, NOT downvote
> 2. Users should only be able to upvote a contract that has NOT already been reviewed, i.e. only 'waitlisted' or 'update requested'
> 
> This is not an admin thing, because users are the ones who will be doing the upvoting. But admin will also be able to see which contracts people most want reviewed (and users can see this too).
> 
> Does that answer your question? Maybe we can merge this to development and then create a new pull to fix these two issues?

Yes these two issues are both present. I don't see any other issues with this.

**Comment by emestabillo** [comment]
I suppose we can merge it and create separate issues.

**Review by emestabillo — DISMISSED** [review]

**Comment by taratip** [comment]
There is no upvote button next to company's contract. Should we fix before merging it or merge this first then create a new issue?

**Comment by emestabillo** [comment]
Hi Tara, ok, I'll try to fix before merging. Thank you!

**Comment by emestabillo** [comment]
@taratip @monroemann @hrbrnd Please check and let me know if upvoting works. Thank you!

**Review by taratip — APPROVED** [review]
The upvote button appears next to company's contract but is not functional yet. We can create a separate issue after merging to development branch.

**Comment by monroemann** [comment]
I'm testing now.  Should have an approval and a merge shortly.  Thank you to everyone for being able to work on multiple projects simultaneously.

**Comment by monroemann** [comment]
Random issue: why is actioncable running when I am on the tosfairness branch:

https://gyazo.com/0dcb2b87e8ff4c4c9357c263f00b6c65

Odd, right?

**Review by monroemann — APPROVED** [review]
Looks good.  I will merge.  Only issue is the one I mentioned above: why is actioncable running when I'm not on bdcommunity repo?

**Pull request merged**
