### PR TITLE
Update scoring system

### PR DESCRIPTION
**Pull request by monroemann**

### CODE REVIEW

**Comment by monroemann** [comment]
Don't know why those other files seem to have been changed, when if you look at the changes, the files weren't really changed.  

Anyway, please review and make sure all looks good.  To me, it seems like the merge won't have any negative effects.

**Comment by monroemann** [comment]
Handles #91

**Review by emestabillo — APPROVED** [review]
It says only whitespace changes for those files.
For the Heroku question: https://devcenter.heroku.com/articles/github-integration-review-apps#creating-review-apps

**Comment by julisbf** [comment]
@monroemann in the home I'm seeing this

screen shot 2018-11-02 at 2 08 34 pm

And when I click "View Details", I see this

screen shot 2018-11-02 at 2 10 19 pm

Is this ok?

**Comment by taratip** [comment]
@julisbf perhaps you don't have contract data created in your machine yet? It will only show contracts that have been reviewed and rated.

**Comment by hrbrnd** [comment]
@julisbf Verified that this does show up because I have some data created from prior: 
image

**Review by hrbrnd — APPROVED** [review]
Looks good! I don't know why it created that and it seems like no negative effects would come up though from the code.

**Comment by julisbf** [comment]
> @julisbf perhaps you don't have contract data created in your machine yet? It will only show contracts that have been reviewed and rated.

@taratip or @hrbrnd , how can I create data in my machine? 

I run `rake db:create`, then `rake db:migrate` and `rake db:seed`. What am missing?

Thanks!

**Comment by monroemann** [comment]
I don’t think we have seed data for TOSfairness. 

A) we should create a seed file
B) in meantime you just have to manually create. A drag, I know...

Back to studying! :D

**Comment by hrbrnd** [comment]
> > @julisbf perhaps you don't have contract data created in your machine yet? It will only show contracts that have been reviewed and rated.
> 
> @taratip or @hrbrnd , how can I create data in my machine?
> 
> I run `rake db:create`, then `rake db:migrate` and `rake db:seed`. What am missing?
> 
> Thanks!

The only way I know how is by running it and manually creating some fake reviews via the website.

**Comment by taratip** [comment]
@julisbf the seed file only creates fake company data. But you still need to create contract and rate it manually.

**Comment by julisbf** [comment]
> @julisbf the seed file only creates fake company data. But you still need to create contract and rate it manually.

I wanted to try everything, that's why I used `rake db:seed` :). Didn't know I had to create the data manually. Thanks for your replies!

**Pull request merged**
